#!/bin/bash
#
#echo -n "Sisesta kellaaeg: " 	##Kysib kellaaja
#read kell			
kell=$(date +"%H") ##Loeb sisendi
error=`tput setaf 1`
reset=`tput sgr0`

if [ $kell -lt 0 -o $kell -gt 23 ]; then	##kui on sisend negatiivne
echo "$error VIGA! $reset"
echo "$error Sisesta positiivne aja vaartus! $reset"
out="$error N2iteks: 23 $reset"

else
if [ $kell -gt 6 -a $kell -lt 12 ]; then
	out="Tere hommikust!"
elif [ $kell -ge 12 -a $kell -lt 16 ]; then
	out="Tere paevast!"
elif [ $kell -ge 16 -a $kell -lt 20 ]; then
	out="Tere ohtust!"
else
	out="Head ood!"

fi
fi
echo "$out" 	##v2ljastab teate
tput sgr0	##taastab originaalv2rvi
