#!/bin/bash
#
# muutujate kasutamise naide
#
#defineerime muutuja ja omistame vaartuse
#v22rtus saadakse whoami k2sust
kasutaja=`whoami`
echo "Tere, $kasutaja"
#loome ja v2ljastame kellajaa
kell=`date +'%H:$M'`
echo "Kell on $kell"
#loome ja v2ljastame kuup2eva
kuupaev=`date +'%d. %B'`
echo "T2na on $kuupaev"
